### ISSUE TITLE
Latex/Katex \text{...} is not correctly rendered

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/doc-builder#397] opened 2023-09-10 10:27 UTC
I'm currently writing a new doc for transformers that uses Latex quite extensively.

When trying to run:
```
doc-builder preview transformers transformers/docs/source/en
```

for [this PR](https://github.com/huggingface/transformers/pull/26058) .

I'm getting the following error message (see [here](https://github.com/huggingface/transformers/actions/runs/6136423243/job/16651257181#step:11:576)):
```
500
dequantize is not defined
ReferenceError: dequantize is not defined
    at llm_tutorial_optimization.mdx:294:32
    at Object.$$render (/tmp/tmpzef5ozu2/kit/node_modules/svelte/internal/index.js:1745:22)
    at Object.default (root.svelte:43:47)
    at eval (/src/routes/__layout.svelte:40:157)
    at Object.$$render (/tmp/tmpzef5ozu2/kit/node_modules/svelte/internal/index.js:1745:22)
    at root.svelte:37:45
    at $$render (/tmp/tmpzef5ozu2/kit/node_modules/svelte/internal/index.js:1745:22)
    at Object.render (/tmp/tmpzef5ozu2/kit/node_modules/svelte/internal/index.js:1753:26)
    at render_response (file:///tmp/tmpzef5ozu2/kit/.svelte-kit/runtime/server/index.js:1166:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

The error stems for [this](https://github.com/huggingface/transformers/pull/26058/files#r1320742110) line:
```
\\( Y = X * \textbf{dequantize}(W); \text{quantize}(W) )\\
```

It seems like rendering text inside latex formulas is not supported at all. E.g. even when trying:

```
$text{Hey}$
```

The doc-builder crashes.

According to the Katex documentation: https://katex.org/docs/supported `\text{...}` is supported. 

Any idea how we could make this work in the HF doc builder? cc @mishig25 maybe?

**Comment by patrickvonplaten** [comment] 2023-09-10 10:35
BTW, this Latex rendering works without a problem for the blog.

**Comment by mishig25** [comment] 2023-09-24 18:20
The issue is completely fixed now https://github.com/huggingface/doc-builder/pull/401

The syntax guide is:

`\\( ... )\\` for inline
example: `\\( Y = X * \textbf{dequantize}(W); \text{quantize}(W) )\\`
[example from transformers here](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/rwkv.md?plain=1#L93)

`$$...$$` for display
example: `$$Y = X * \textbf{dequantize}(W); \text{quantize}(W)$$`
[example from transformers here](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/rwkv.md?plain=1#L107)

**Closed by mishig25** 2023-09-24 18:20 UTC
