### ISSUE TITLE
Add missing Content-Language header in generated HTML page

### ISSUE THREAD

**Issue by wonhyeongseo** [huggingface/doc-builder#393] opened 2023-08-25 01:30 UTC
## Description

Hello @mishig25 ,

I am writing to raise a concern about the lack [content-language headers (link to MDN docs)](https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/Content-Language) in the generated HTML pages of the huggingface documentation. This has caused problems for using LangChain to make a QA system with the Korean Documentation.

## Expected Behavior

LangChain and other software should be able to detect the content language automatically with the header in-place.

## Current Behavior

LangChain fails to retrieve the content when through a browser the docs work fine. Please see [sim-so's comment](https://github.com/huggingface/doc-builder/issues/393#issuecomment-1692925842) for details.

## Steps to Reproduce

1. Create a new LangChain project.
2. Try to retrieve the translated Hugging Face documentation via the webbrowser plugin.
  ```js
    const result = await browser.call(
    `"https://huggingface.co/docs/transformers/main/ko/pipeline_tutorial","pipeline()에서 배치 사이즈는 어떤 역할을 하나요?"`
  );
  ```

## Possible Solution

Use the source directory information and put it in the header at build time.

Please let me know if you need any further information. I intend to work on this issue with @sim-so to send a PR.

Thank you for your attention to this matter.

**Comment by sim-so** [comment] 2023-08-25 07:51
@wonhyeongseo, thank you for opening the issue! I added my experience regarding it.

I found the problem using LangChiain's `WebBaseLoader`. When you execute the code below:
```
from langchain.document_loaders import WebBaseLoader

url = 'https://huggingface.co/docs/transformers/v4.32.0/ko/tasks/sequence_classification'
loader = WebBaseLoader(url)
data = loader.load()
for k, v in data[0].metadata.items():
    print(f"{k} : {v}")
content = data[0].page_content
print("content : ")
content[5000:5300] # to truncate the front of the documents with many new lines.
```
you can get the output as follows:
```
source : https://huggingface.co/docs/transformers/v4.32.0/ko/tasks/sequence_classification
title : í…�ìŠ¤íŠ¸ ë¶„ë¥˜
description : Weâ€™re on a journey to advance and democratize artificial intelligence through open source and open science.
language : No language found.
content : 
‹¤.
ì�´ ê°€ì�´ë“œì—�ì„œ í•™ìŠµí•  ë‚´ìš©ì�€:
IMDb ë�°ì�´í„°ì…‹ì—�ì„œ DistilBERTë¥¼ íŒŒì�¸ íŠœë‹�í•˜ì—¬ ì˜�í™” ë¦¬ë·°ê°€ ê¸�ì •ì �ì�¸ì§€ ë¶€ì •ì �ì�¸ì§€ íŒ�ë‹¨í•©ë‹ˆë‹¤.
ì¶”ë¡ ì�„ ìœ„í•´ íŒŒì�¸ íŠœë‹� ëª¨ë�¸ì�„ ì‚¬ìš©í•©ë‹ˆë‹¤.
ì�´ íŠœí† ë¦¬ì–¼ì—�ì„œ ì„¤ëª…í•˜ëŠ” ì�‘ì—…ì�€ ë‹¤ì�Œ ëª¨ë�¸ ì•„í‚¤í…�ì²˜ì
```
I guess the problem is related to `Response.apparent_encoding` leveraged by `WebBaseLoader`. `chardet.detect()`, which assigns the apparent_encoding to a Response object, cannot detect a proper encoding for the document.

```
import requests

response = requests.get(url)
print(f"Encoding : {response.encoding}")
print(f"Apparent Encoding : {response.apparent_encoding}")
print(f"Chardet Detected Encoding : {chardet.detect(response.content)}")
```
```
Encoding : utf-8
Apparent Encoding : Windows-1254
Chardet Detected Encoding : {'encoding': 'Windows-1254', 'confidence': 0.31608697460562435, 'language': 'Turkish'}
```
Additionally, I tried the above with other web pages containing a content-language header and found that they can be detected with proper encodings. 🙂

**Comment by mishig25** [comment] 2023-08-25 10:50
@wonhyeongseo @sim-so thank you very much for a detailed description of the issue. The problem will be fixed soon. I will keep you updated 👍

**Closed** 2023-08-26 13:39 UTC

**Comment by mishig25** [comment] 2023-08-28 16:11
@wonhyeongseo @sim-so the problem should be fixed now. Please let me know if that's not the case
